### ISSUE TITLE
Consuming 99% CPU, restarts itself (must auth many times)

### ISSUE THREAD

**Issue by spikespaz** [jirutka/swaylock-effects#67]
Using Hyprland `master`, Nixpkgs `nixos-unstable`, also using [#49](https://github.com/jirutka/swaylock-effects/pull/49). I have three monitors, middle, left, and top. Coordinates: middle `(1920, 1440)`, left `(0, 1440)`, top `(1600, 0)`. Sizes and scaling: middle `(2880, 1800, 1.5)` virtual `(1920, 1200)`, left `(1920, 1080, 1.0)`, top `(2560, 1440, 1.0)`.

With Factorio (Xwayland) open on the top monitor, I noticed the game stuttering. I check `top`, and see that `swaylock` is using >99% CPU. Killed the PID, then `swaylock` restarts. Factorio continues displaying animation frames while the other two screens are showing the lock screen as configured. I then had to authenticate several times because `swaylock` restarts itself after a *successful* authentication. Eventually, maybe 5 tries (has been more historically), it finally goes away and there is no more `swaylock` process.

Questions:
1. What is going on with Factorio, why does it render above the lock screen surface?
2. Why was there a zombie `swaylock` process using infinite cycles?
3. Is #49 malicious?
4. Why did the process exit gracefully when I issued `kill` (`TERM`: 15) instead of `kill -9` (`KILL`: 9)? Shouldn't it render the session useless if it is killed, and disallow `TERM`?
5. Why did it restart itself many times?
6. Are there several unrelated problems here?

The reason I ask all of these in a single issue is because all of these symptoms cropped up at the same time (considerable time after making #49 part of my setup I might add).

**Comment by spikespaz** [comment]
This just in: `swaylock` started randomly, despite me playing a game (active HID input). This time, Factorio was covered by the surface. When I authenticated, the game's keyboard and mouse was unresponsive until I (1) focused another window, (2) resized that window, (3) resized Factorio. After this sequence, I can continue sending input events to Factorio.

**Comment by jirutka** [comment]
Can you please test if it’s happening even on v1.7.0.0 without #49?

**Comment by kiritofeng** [comment]
I've also had problems running #49; sometimes when I unlock my computer from sleep, `swaylock` continue to run in the background; I get
```
$ ps aux | grep swaylock
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
<redacted>   3803581  277  0.5 206512 94832 ?        SLl  10:14  98:34 swaylock --fingerprint --screenshots --effect-blur 10x5 --clock --indicator --text-color FFFFFFFF --grace 1 --fade-in 1 --font DejaVu Sans Mono
<redacted>   3803583  0.0  0.0  22036  4712 ?        S    10:14   0:00 swaylock --fingerprint --screenshots --effect-blur 10x5 --clock --indicator --text-color FFFFFFFF --grace 1 --fade-in 1 --font DejaVu Sans Mono
```
and my computer reports high (~80%) CPU usage, killing `swaylock` and waiting a few seconds massively drops CPU usage (~5%).

I am running on Arch Linux 6.14.10, `swaylock-effects` version
```
swaylock version v1.7.0.0-1-g496059a (" __DATE__ ", branch 'makepkg')
```
(built from the AUR package with #49 patched in).

**Comment by kiritofeng** [comment]
I dumped the stack of the process in the "unlocked but eating up CPU state" (with #49) and got
```
#0  0x00005614b00d1799 in blur_v._omp_fn () at ../effects.c:218
#1  0x00007f4c89fdf9a9 in GOMP_parallel
    (fn=0x5614b00d1600 <blur_v._omp_fn>, data=0x7ffcd661b920, num_threads=12, flags=0)
    at /usr/src/debug/gcc/gcc/libgomp/parallel.c:178
#2  0x00005614b00d4ec6 in blur_v
    (dest=0x5614e1e0ba00, src=0x5614e26d5a10, width=<optimized out>, height=<optimized out>, radius=<optimized out>) at ../effects.c:182
        minradius = <optimized out>
#3  blur_once
    (dest=0x5614e1e0ba00, src=0x5614e15419f0, scratch=0x5614e26d5a10, width=<optimized out>, height=<optimized out>, radius=<optimized out>) at ../effects.c:228
#4  effect_blur
    (scale=1, dest=0x5614e1e0ba00, src=0x5614e15419f0, width=<optimized out>, height=<optimized out>, radius=<optimized out>, times=<optimized out>) at ../effects.c:244
        tmp = 0x5614e1e0ba00
        i = 3
        origdest = <optimized out>
        scratch = 0x5614e26d5a10
        origdest = <optimized out>
        scratch = <optimized out>
        i = <optimized out>
        tmp = <optimized out>
#5  run_effect (surface=0x5614e14e21e0, effect=effect@entry=0x5614e14b3240, scale=1) at ../effects.c:593
        surf = 0x5614e14cf3f0
#6  0x00005614b00c7cac in swaylock_effects_run
    (scale=1, surface=<optimized out>, effects=<optimized out>, count=1) at ../effects.c:721
        effect = 0x5614e14b3240
        i = <optimized out>
#7  apply_effects (state=0x5614b00dffa0 <state>, scale=1, image=<optimized out>) at ../main.c:530
#8  main (argc=<optimized out>, argv=<optimized out>) at ../main.c:1995
        line_mode = LM_LINE
        config_path = 0x0
        result = <optimized out>
        registry = <optimized out>
        surface = <optimized out>
        daemonfd = 22036
        iter_image = 0x5614e14bccf0
        temp = 0x5614e14bccf0
        fingerprint_state = {error = 0x7ffcd661ba60, started = 1686879744, completed = 1867833534, match = -698238336, status = "\374\177\000\000 eK\341\024V\000\000\240\272a\326\374\177\000\000Ž9\212L\177\000\000ؼa\326\374\177\000\000\020\273a\326\374\177\000\000\017\000\000\000\000\000\000\000X\274a\326\374\177\000\000ؼa\326\374\177\000\000\230\227P\212L\177\000\000\260\273a\326\374\177\000\000\225\313K\212L\177\000\000\260\273a\326\374\177\000\000\372E\375\211\004", '\000' <repeats 22 times>, manager = 0x0, connection = 0x0, device = 0x0, sw_state = 0x0}
```
